services:
  - type: web
    name: he-thong-cham-trac-nghiem
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
